# Lecture 09

In [1]:
import numpy as np
import pandas as pd

In [2]:
!unzip -u ../../lec/lec06/data/imdb_perf_lecture.zip -d ../../lec/lec06/data/.

Archive:  ../../lec/lec06/data/imdb_perf_lecture.zip

In [3]:
!psql -h localhost -c 'DROP DATABASE IF EXISTS imdb_perf_lecture'
!psql -h localhost -c 'CREATE DATABASE imdb_perf_lecture' 
!psql -h localhost -d imdb_perf_lecture -f ../../lec/lec06/data/imdb_perf_lecture.sql

ERROR:  database "imdb_perf_lecture" is being accessed by other users
DETAIL:  There is 1 other session using the database.
ERROR:  database "imdb_perf_lecture" already exists
SET
SET
SET
SET
SET
 set_config
------------

(1 row)

SET
SET
SET
SET
SET
SET
psql:../../lec/lec06/data/imdb_perf_lecture.sql:30: ERROR:  relation "actors" already exists
ALTER TABLE
psql:../../lec/lec06/data/imdb_perf_lecture.sql:42: ERROR:  relation "cast_info" already exists
ALTER TABLE
psql:../../lec/lec06/data/imdb_perf_lecture.sql:56: ERROR:  relation "movies" already exists
ALTER TABLE
psql:../../lec/lec06/data/imdb_perf_lecture.sql:845954: ERROR:  duplicate key value violates unique constraint "actor_pkey"
DETAIL:  Key (id)=(1) already exists.
CONTEXT:  COPY actors, line 1
^C
Cancel request sent
psql:../../lec/lec06/data/imdb_perf_lecture.sql:3057898: ERROR:  canceling statement due to user request
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."actors" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"

# Structural Transformation: From Relations to Matrices and Back
- Matrix $\rightarrow$ Relational works.
- Relational $\rightarrow$ Matrix sometimes works!
- But how?

To start, let's take our matrix in `mm.txt`, and load it into Pandas.

In [4]:
import pandas as pd

In [5]:
mm = pd.read_csv('data/mm.txt', header=0)
mm

,Year,OCT,NOV,DEC,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP
0,2002,545.92,3115.08,3996.76,1815.74,1204.14,1644.02,795.92,540.24,112.62,79.52,22.20,171.70
1,2003,55.41,1242.23,2976.94,797.72,836.01,1026.11,1571.27,468.59,24.93,98.33,267.40,99.20
2,2004,55.90,834.40,2311.72,942.75,2019.22,399.52,339.18,251.64,72.38,55.57,116.74,97.48
3,2006,347.22,908.44,2981.16,1793.97,995.27,2031.19,1602.55,287.21,102.44,90.31,18.75,33.76
4,2005,1449.23,619.77,1789.93,1777.23,1055.41,1472.91,743.11,1113.26,309.19,46.61,86.51,93.98
5,2007,178.81,942.89,1279.33,320.66,1615.47,317.77,519.85,150.15,85.32,102.60,62.74,164.02
6,2008,612.92,329.64,1189.43,2153.17,1007.57,316.55,153.53,255.80,42.45,41.73,36.83,12.59
7,2009,272.27,777.81,1102.87,533.64,1479.80,881.30,297.80,580.28,320.84,35.95,53.25,42.99
8,2010,722.61,379.36,1029.03,1780.54,1136.93,814.83,1225.52,487.75,146.90,38.05,46.77,88.72
9,2011,1059.68,1016.81,2555.51,463.27,1059.94,2173.84,465.80,552.36,350.04,84.51,21.59,76.77
10,2020,56.21,311.24,1202.38,578.53,70.34,789.14,509.50,375.76,70.86,17.71,25.99,21.65
11,2012,527.67,523.53,156.69,1066.21,421.75,1643.46,828.51,115.19,164.73,98.85,92.70,45.65
12,2014,119.18,281.26,178.54,233.12,1314.08,978.52,376.71,179.59,42.21,96.86,163.17,244.05
13,2013,376.65,1131.15,1759.84,338.40,189.12,391.51,259.37,254.56,142.22,72.63,96.91,343.69
14,2015,342.81,551.60,1654.38,149.87,860.72,243.26,343.53,338.50,109.07,201.23,49.52,84.94
15,2016,305.11,635.79,1530.09,1754.74,367.08,1395.37,427.64,245.77,110.11,37.56,28.19,52.88
16,2017,1175.34,581.67,1155.19,2628.17,2110.15,751.90,825.07,153.14,118.32,53.72,72.88,156.63
17,2018,130.64,967.23,118.69,847.21,201.54,1540.98,578.42,201.33,43.35,68.03,22.84,14.06
18,2019,199.39,754.07,585.14,1282.06,2261.94,1090.67,442.48,743.01,48.86,25.14,48.34,208.95

## What does an unpivot look like (Matrix -> Relational)?

In [6]:
mm_melted = mm.melt(id_vars=['Year'])
mm_melted

     Year variable    value
0    2002      OCT   545.92
1    2003      OCT    55.41
2    2004      OCT    55.90
3    2006      OCT   347.22
4    2005      OCT  1449.23
..    ...      ...      ...
223  2015      SEP    84.94
224  2016      SEP    52.88
225  2017      SEP   156.63
226  2018      SEP    14.06
227  2019      SEP   208.95

[228 rows x 3 columns]

Thanks to the `id_var` parameter, the `Year` column is named and repeated for all other (variable=column name, value=value) elements in the row.

In [ ]:
mm_melted[mm_melted['Year'] == 2002]

## PIVOT(UNPIVOT) = ??

In [8]:
#mm_melted.pivot(index='variable', columns='Year')
mm_melted.pivot(index='variable', columns='Year')

            value                                                        \
Year         2002     2003     2004     2005     2006     2007     2008
variable
APR        795.92  1571.27   339.18   743.11  1602.55   519.85   153.53
AUG         22.20   267.40   116.74    86.51    18.75    62.74    36.83
DEC       3996.76  2976.94  2311.72  1789.93  2981.16  1279.33  1189.43
FEB       1204.14   836.01  2019.22  1055.41   995.27  1615.47  1007.57
JAN       1815.74   797.72   942.75  1777.23  1793.97   320.66  2153.17
JUL         79.52    98.33    55.57    46.61    90.31   102.60    41.73
JUN        112.62    24.93    72.38   309.19   102.44    85.32    42.45
MAR       1644.02  1026.11   399.52  1472.91  2031.19   317.77   316.55
MAY        540.24   468.59   251.64  1113.26   287.21   150.15   255.80
NOV       3115.08  1242.23   834.40   619.77   908.44   942.89   329.64
OCT        545.92    55.41    55.90  1449.23   347.22   178.81   612.92
SEP        171.70    99.20    97.48    93.98    33.76   164.02    12.59

                                                                         \
Year         2009     2010     2011     2012     2013     2014     2015
variable
APR        297.80  1225.52   465.80   828.51   259.37   376.71   343.53
AUG         53.25    46.77    21.59    92.70    96.91   163.17    49.52
DEC       1102.87  1029.03  2555.51   156.69  1759.84   178.54  1654.38
FEB       1479.80  1136.93  1059.94   421.75   189.12  1314.08   860.72
JAN        533.64  1780.54   463.27  1066.21   338.40   233.12   149.87
JUL         35.95    38.05    84.51    98.85    72.63    96.86   201.23
JUN        320.84   146.90   350.04   164.73   142.22    42.21   109.07
MAR        881.30   814.83  2173.84  1643.46   391.51   978.52   243.26
MAY        580.28   487.75   552.36   115.19   254.56   179.59   338.50
NOV        777.81   379.36  1016.81   523.53  1131.15   281.26   551.60
OCT        272.27   722.61  1059.68   527.67   376.65   119.18   342.81
SEP         42.99    88.72    76.77    45.65   343.69   244.05    84.94


Year         2016     2017     2018     2019     2020
variable
APR        427.64   825.07   578.42   442.48   509.50
AUG         28.19    72.88    22.84    48.34    25.99
DEC       1530.09  1155.19   118.69   585.14  1202.38
FEB        367.08  2110.15   201.54  2261.94    70.34
JAN       1754.74  2628.17   847.21  1282.06   578.53
JUL         37.56    53.72    68.03    25.14    17.71
JUN        110.11   118.32    43.35    48.86    70.86
MAR       1395.37   751.90  1540.98  1090.67   789.14
MAY        245.77   153.14   201.33   743.01   375.76
NOV        635.79   581.67   967.23   754.07   311.24
OCT        305.11  1175.34   130.64   199.39    56.21
SEP         52.88   156.63    14.06   208.95    21.65

In [ ]:
mm_melted.dtypes

### Extra Columns
Let's go back to `mmp.txt`. 
- Matrix or relation? 
- Try doing some PIVOT/UNPIVOT work on this.

In [ ]:
mmp = pd.read_csv('data/mmp.txt', header=0)
mmp

In [ ]:
# Unpivot
mmp_melted = mmp.melt(id_vars=['Location', 'Station', 'Year'])
mmp_melted

In [ ]:
# Repivot the unpivot

# mmp_tt = mmp_melted.pivot(index='Year', columns='variable')
mmp_tt = mmp_melted.pivot(index=['Location', 'Station', 'Year'], columns='variable')
mmp_tt

In [ ]:
mmp_tt.reset_index()

# [Extra] Multisets to Sets

### Set up connections and schema

In [ ]:
%reload_ext sql
%sql postgresql://127.0.0.1:5432/postgres
import pandas as pd

In [ ]:
%%sql
DROP TABLE IF EXISTS blue;
DROP TABLE IF EXISTS red;
CREATE TABLE blue (last TEXT, first TEXT);
CREATE TABLE red (last TEXT, first TEXT);

INSERT INTO blue VALUES ('Wang', 'Daisy');
INSERT INTO blue VALUES ('Wang', 'Daisy');
INSERT INTO blue VALUES ('Wang', 'Xin');

INSERT INTO red VALUES ('Wang', 'Daisy');
INSERT INTO red VALUES ('Wang', 'Xin');
INSERT INTO red VALUES ('Wang', 'Xin');

SELECT * FROM blue;

In [ ]:
%sql SELECT * FROM red;

## Representing multiset relations as counted-set relations

### Use a CTAS statement with group by to convert standard tables to counted-set tables

In [ ]:
%%sql
DROP TABLE IF EXISTS bluem;
CREATE TABLE bluem AS 
    SELECT *, COUNT(*) AS multiplicity
    FROM blue
    GROUP BY last, first;

SELECT * FROM bluem;

In [ ]:
%%sql
DROP TABLE IF EXISTS redm;
CREATE TABLE redm AS
    SELECT *, COUNT(*) AS multiplicity
    FROM red
    GROUP BY last, first;

SELECT * FROM redm;

### How do we make selection on counted-set tables work like multisets?

This works exactly the same in both cases. There's nothing special here. Applying `WHERE` filters on a counted-set will always yield a set back, because you're only removing rows from a set. By definition, this cannot create an entity that is not a set.

In [ ]:
%%sql
-- sigma on multiset
SELECT * FROM blue 
WHERE first = 'Daisy';

In [ ]:
%%sql
-- sigma on counted set
SELECT * FROM bluem WHERE first = 'Daisy';

### What about projection?

We might want to be a bit careful here. See, what defines a set uniquely is its key, and in this case, the key is the combination of `(last, first)`. Simply having `last` or just having `first` is not enough to uniquely identify a row.

In [ ]:
%%sql
-- pi on multiset
SELECT last FROM blue;

In fact, you can see that if you simply selected `last` from a counted-set, you'd get a multi-set as your output.

In [ ]:
%%sql
SELECT last FROM bluem;

To convert this to a counted-set again, you need to sum up the multiplicities of the tuples that the `last` field came from.

In [ ]:
%%sql
-- pi on counted set
SELECT last, SUM(multiplicity)
FROM bluem group by last;

### What about cross-product?

In [ ]:
%%sql
-- x on multiset
SELECT * FROM blue, red;

Next, convert *the output* of a multiset cross-product to a counted set as we did before. This is our desired result:

In [ ]:
%%sql
-- convert multiset x to counted set
WITH cte(blast, bfirst, rlast, rfirst)
    AS (SELECT * FROM blue, red)
SELECT *, COUNT(*)
  from cte
GROUP BY blast, bfirst, rlast, rfirst;

Now, what went on in the arithmetic here? We can think this through by pushing the arithmetic into the query!

First, what do you get with naive cross-product of counted sets? You get the names from each table, along with the number of times that each name showed up in its respective table. So, for example, `('Wang', 'Xin')` showed up once in `blue` and twice in `red`.

In [ ]:
%%sql
SELECT * FROM bluem, redm;

What does each row tell us individually? Each row tells us the number of times that the name from the left must be matched with the name from the right in the original cross product between `blue` and `red`. So if you multiply the multiplicities together, you'll get the number of instances of each ordered pair of names in the final cross product

In [ ]:
%%sql
-- fix multiplicity per row
SELECT b.last, b.first, r.last, r.first, b.multiplicity*r.multiplicity
FROM bluem b, redm r;

If we simply wanted to drop duplicates instead of monitoring how many there were (the point of a counted-set), our life would have been a lot easier...

In [ ]:
%%sql
SELECT DISTINCT b.last, b.first, r.last, r.first
FROM blue b, red r;

# [Scratch] Transposing Demo Code

In [ ]:
%reload_ext sql
%sql postgresql://127.0.0.1:5432/postgres
import pandas as pd

In [ ]:
%%sql
DROP TABLE IF EXISTS example;
CREATE TABLE example(name text, age integer, gpa float);
INSERT INTO example VALUES
       ('Patty Perfect', 22, 4.0),
       ('Sameer Soclose', 20, 3.99),
       ('Jacob Excellent', 21, 3.93);

In [ ]:
df = %sql SELECT * FROM example;
df = df.DataFrame()

In [ ]:
display(df)
display(df.dtypes)

In [ ]:
dft = df.transpose()
display(dft)
display(dft.dtypes)

In [ ]:
dftt = df.transpose().transpose()
display(dftt)
display(dftt.dtypes)

In [ ]:
dftt['age'] = dftt['age'].astype(int)
dftt['gpa'] = dftt['gpa'].astype(float)

In [ ]:
dftt.dtypes

In [ ]:
mat = np.array([[1, 0, 0, 1, 20000],
          [0, 1, 0, 2, 10011],
          [0, 0, 1, 3, 50000],
          [0, 0, 1, 3, 10000]])
mat

In [ ]:
df = pd.DataFrame({'CompanyName': ['VW', 'Acura', 'Hona', 'Honda'],
              'Categorical Value': [1, 2, 3, 3],
              'Price': [20000, 10011, 50000, 10000]})
df

In [ ]:
df.dtypes

In [ ]:
# %sql --persist df