# Discussion 05 Notebook

This notebook is an accompaniment to the associated discussion worksheet handout.

# Section III. Pivoting and Unpivoting

## Question 11

**_Pivoting._** Write a Pandas expression to reshape the following table such that its columns are the 3
types of metals in the `CType` column, and whose values are taken from the `USD` column. Also write the
resulting table.

In [1]:
import pandas as pd
data_q1 = {
    'Item': ['Item0', 'Item0', 'Item1', 'Item1'],
    'CType': ['Gold', 'Bronze', 'Gold', 'Silver'],
    'USD': ['$1', '$2', '$3', '$4'],
    'EUR': ['€1', '€2', '€3', '€4']
}
df_q1  = pd.DataFrame(data_q1)
df_q1

    Item   CType USD EUR
0  Item0    Gold  $1  €1
1  Item0  Bronze  $2  €2
2  Item1    Gold  $3  €3
3  Item1  Silver  $4  €4

In [3]:
# Write your code here

## Question 12

**_Unpivoting._** Write a Pandas expression to reshape the following table from a _wide_ shape into a long shape, using the student and school columns as identifiers, and the rest of the subjects as variables.
Also write the resulting table. Hint: `use df.melt()`.

In [4]:
data_q2 = {
    'student': ['Andy', 'Bernie', 'Cindy', 'Deb'],
    'school': ['Z', 'Y', 'Z', 'Y'],
    'english': [90, 100, 60, 150],
    'math': [60, 5, 99, 4],
    'physics': [80, 4, 100, 5]
}

df_q2 = pd.DataFrame(data_q2)
df_q2

  student school  english  math  physics
0    Andy      Z       90    60       80
1  Bernie      Y      100     5        4
2   Cindy      Z       60    99      100
3     Deb      Y      150     4        5

In [6]:
# Write your code here